language: python
python: 
  - "3.6"
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install coverage
before_script:
 - cd upwork
script:
# - coverage run -m -p unittest test_notification.py
# - coverage report -m
- py.test upwork  -v --cov upwork --cov-report term-missing
after_success:
  - coveralls
