language: python
python: 
  - "3.6"
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install coverage
script:
  - py.test upwork  -v --cov upwork --cov-report term-missing
after_success:
  - coveralls
